export const ADD_FORM = 'ADD_FORM';
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const RESET_ERROR = 'RESET_ERROR';

export const FORM_REQUEST_START = 'FORM_REQUEST_START';
export const FORM_REQUEST_SUCCESS = 'FORM_REQUEST_SUCCESS';
export const FORM_REQUEST_FAIL = 'FORM_REQUEST_FAIL';

export const UPDATE_FORM_REQUEST_START = 'UPDATE_FORM_REQUEST_START';
export const UPDATE_FORM_REQUEST_SUCCESS = 'UPDATE_FORM_REQUEST_SUCCESS';
export const UPDATE_FORM_REQUEST_FAIL = 'UPDATE_FORM_REQUEST_FAIL';

export const FETCH_FORMS_DEPARTMENT = 'FETCH_FORMS_DEPARTMENT';
export const FETCH_FORMS_USER_ASSIGNED = 'FETCH_FORMS_USER_ASSIGNED';
export const FETCH_FORMS_USER_REQUESTED = 'FETCH_FORMS_USER_REJECTED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_LOGOUT = 'REGISTER_LOGOUT';
export const SWITCH_LOGIN = 'SWITCH_LOGIN';

export const RESET_AUTH = 'RESET_AUTH';
export const RESET_DEPARTMENT = 'RESET_DEPARTMENT';

export const DEPARTMENT_LOADING_START = 'DEPARTMENT_LOADING_START';
export const DEPARTMENT_LOADING_STOP = 'DEPARTMENT_LOADING_STOP';